### ISSUE TITLE
how do I use the Irish Grid Ref?

### ISSUE THREAD

**Issue by rantool** [dvdoug/PHPCoord#11]
I am seeing error when I try to load IrishGridRef.php 
PHP Fatal error:  Class 'PHPCoord\TransverseMercator' not found in /home/site/public_html/PHPCoord-master/IrishGridRef.php on line 16

**Comment by dvdoug** [comment]
Hi

How have you installed this, via Composer or manually? Do you have an autoloader?

**Comment by dvdoug** [comment]
Closing for no response
