### ISSUE TITLE
Accuracy of Lat/Lng to Easting/Northing

### ISSUE THREAD

**Issue by hill79** [dvdoug/PHPCoord#17]
I'm having issues with the accuracy of the conversion between a given set of Lat Lng coordinates and their equivalent Easting / Northing's.

**Example**
Lat: 51.57166, Lng: -3.21813 is a bus station in Caerphilly [map](https://goo.gl/maps/SYDav41rvAn)

Using
`$LatLng = new LatLng(51.57166, -3.21813, 0, RefEll::airy1830());
  $OSRef = $LatLng->toOSRef();`

Returns
`
[x:protected] => 311261
[y:protected] => 185622
`
Which is around 80 meters away [map](https://gridreferencefinder.com/?gr=ST1558886621|315588_s__c__s_186621|1&v=r)

**Comment by dvdoug** [comment]
Google uses WGS84, try using RefEll::wgs84() instead and I think you'll find the co-ordinates much closer to where you're expecting

**Comment by hill79** [comment]
Thanks - that's perfect! Appreciate the guidance.
