### ISSUE TITLE
Feature request: support Irish grid

### ISSUE THREAD

**Issue by robations** [dvdoug/PHPCoord#2]
As far as I can tell (I don't have much experience with GIS) this would be very similar or the same as the OSRef, just with a few different constants. I've been trying to follow along here to implement this:

https://www.ordnancesurvey.co.uk/docs/support/guide-coordinate-systems-great-britain.pdf

though so far pretty confused by the various standards, and statements like "this is not a transformation", which begs the question, "what is and isn't a transformation?".

**Comment by robations** [comment]
I managed to implement this by copying the `OSRef` class as `IrishGridRef` and changing the relevant constants. It seems to work, at least to the low precision I need at the moment.

Obviously this isn't a maintainable solution, but doing this properly will need some refactoring to avoid repeating all the logic that's currently in `OSRef::toLatLng()`. If you're interested I could perhaps look at this and submit a PR.

**Comment by dvdoug** [comment]
Yes, I'd happily take a PR to add support

**Comment by dvdoug** [comment]
Now available in v2, but please note I refactored and changed the API a bit so it's not a drop-in upgrade

**Comment by robations** [comment]
That's great — I didn't ever get back to this and I've been avoiding coding outside work for sanity reasons :)
