### ISSUE TITLE
Possibility to map UTM coordinates to a different zone?

### ISSUE THREAD

**Issue by marcoliverteschke** [dvdoug/PHPCoord#23]
Hi,

question: is it possible with this library to map a set of UTM coordinates to a neighboring zone?

Long-winded explanation: for a project we are required to support a maps provider who, because of reasons, expects all coordinates for markers to be in UTM zone 32N. 
But when I, for example, drop in the LatLng for a spot in Berlin and convert to UTM, I get coordinates for zone 33N, which is correct, but on that map results in a marker nowhere near Berlin.
Is it, with this library, somehow possible to convert UTM coordinates between zones?

Best regards
Marc-Oliver

**Comment by dvdoug** [comment]
How does this work - does the fake zone just overflow the usual boundary?

Can you give me some lat/lng examples along with what this particular provider expects the output to be? It shouldn't be too hard to add an override mechanism in, but I'd to make sure the output of the calcuation matches what you expect.

**Comment by marcoliverteschke** [comment]
Hi!

Yes, as far as I understand them, even though 32N ends somewhere in the middle of Germany, for eastern Germany they would expect coordinates that are calculated as if zone 32N never ended and just stretched out forever.

So here's an example with an address in Berlin:

**longlat** 
13.375520 52.518590

**PHPCoord returns** 
389854 5819958 in Zone 33N

**What they expect (calculated with https://mygeodata.cloud/cs2cs/)**
796823.561343 5827721.40417 in Zone 32N

Hope this helps?

**Comment by dvdoug** [comment]
Thanks @marcoliverteschke , that should be doable then. I'll add this to my todo list

**Comment by mpijierro** [comment]
Hello @marcoliverteschke,

Did you manage to do the mapping? I have a similar case. I have longitude and latitude coordinates that are in zone 29 and they want everything referenced with respect to zone 30.

@dvdoug, Is it possible to do this with PHPCoord?

Thank you for you work

**Comment by dvdoug** [comment]
Hi @mpijierro 

It's not currently possible inside PHPCoord directly since the zone is auto-calculated from the coordinate. However I am currently working on a rewrite of the library that will support this usecase - 🤞 I aim to finish in the Xmas-New Year period 🤞

**Comment by mpijierro** [comment]
ok @dvdoug , we will wait patiently. Thank you very much for your work and your effort.

**Comment by dvdoug** [comment]
Update: I should be ready to tag a beta release tomorrow, the API of the rewrite is fairly stable now. Just trying to decide on the minimum PHP version to support.

@mpijierro What PHP version do you need?

**Comment by dvdoug** [comment]
Example of usage with the rewritten API (taken from tests):

```php
    // Issue #23
    public function testBerlinPointPlacedIntoZone33WhenCalculatedAutomatically(): void
    {
        $from = GeographicPoint::create(new Degree(52.518590), new Degree(13.375520), null, Geographic2D::fromSRID(Geographic2D::EPSG_WGS_84));
        $toCRS = Projected::fromSRID(Projected::EPSG_WGS_84_UTM_GRID_SYSTEM_NORTHERN_HEMISPHERE);
        $to = $from->convert($toCRS);

        self::assertEqualsWithDelta(33389776, $to->getEasting()->getValue(), 1);
        self::assertEqualsWithDelta(5819959, $to->getNorthing()->getValue(), 1);
    }

    // Issue #23
    public function testBerlinPointNotZone32(): void
    {
        $this->expectException(UnknownConversionException::class);
        $from = GeographicPoint::create(new Degree(52.518590), new Degree(13.375520), null, Geographic2D::fromSRID(Geographic2D::EPSG_WGS_84));
        $toCRS = Projected::fromSRID(Projected::EPSG_WGS_84_UTM_ZONE_32N);
        $to = $from->convert($toCRS);
    }

    // Issue #23
    public function testBerlinPointZone32WhenForced(): void
    {
        $from = GeographicPoint::create(new Degree(52.518590), new Degree(13.375520), null, Geographic2D::fromSRID(Geographic2D::EPSG_WGS_84));
        $toCRS = Projected::fromSRID(Projected::EPSG_WGS_84_UTM_ZONE_32N);
        $to = $from->convert($toCRS, true);

        self::assertEqualsWithDelta(796823.561, $to->getEasting()->getValue(), 0.001);
        self::assertEqualsWithDelta(5827721.404, $to->getNorthing()->getValue(), 0.001);
    }

```

**Comment by mpijierro** [comment]
Hi @dvdoug ,

I am using version 7.4.

Thanks.

**Comment by marcoliverteschke** [comment]
Hi @dvdoug,

for what it's worth, we use your library in the context of a Drupal 9 distribution, so we currently support PHP 7.3. If it's not too much trouble to support 7.3, we'd greatly appreciate that!

If you land on 7.4, that's cool, too. We'll then just have to push the update to a later release with bumped requirements.

**Comment by dvdoug** [comment]
The difference between 7.4 and 7.3 turns out to mostly be removing type information (mostly typed properties, some return types with covariance). That's annoying, because putting them back would take a while 😅.

The plan I've landed is to keep the correct types on master for longer term development (PHPCoord 4.1 and up), but I'll create a seperate branch for the 4.0.0-4.0.x series that has a PHP7.3 patch applied.

**Comment by dvdoug** [comment]
Beta released: https://github.com/dvdoug/PHPCoord/releases/tag/v4.0.0beta1

**Comment by dvdoug** [comment]
Stable released: See https://www.phpcoord.net/en/stable/coordinate_conversions.html for docs
