### ISSUE TITLE
Uncaught Error: Class 'PHPCoord\CoordinateReferenceSystem\Projected' not found

### ISSUE THREAD

**Issue by kasperkamperman** [dvdoug/PHPCoord#33]
I get a PHP error when running a simple example. Maybe I misunderstand namespaces, but I'm following the examples.
```Uncaught Error: Class 'PHPCoord\CoordinateReferenceSystem\Projected' not found```

Reproduce:

step 1:
composer require php-coord/php-coord

step 2:
create php file based on this example:
https://www.phpcoord.net/en/stable/creating_points_projected.html

```
<?php
require_once __DIR__ . '/vendor/autoload.php';

use PHPCoord\CoordinateReferenceSystem\Projected;
use PHPCoord\ProjectedPoint;
use PHPCoord\UnitOfMeasure\Length\Metre;

// Nelson's Column in British National Grid (unknown date), traditional arguments
$crs = Projected::fromSRID(Projected::EPSG_OSGB36_BRITISH_NATIONAL_GRID);
$point = ProjectedPoint::createFromEastingNorthing(
    new Metre(530017),
    new Metre(180419),
    $crs
);
?>
```

**Comment by sttrsttr** [comment]
I'm just here to search for clues to why I am having similar issue right now.

PHP Fatal error:  Uncaught Error: Class 'PHPCoord\CoordinateReferenceSystem\Geographic2D' not found 

I've added the files to my composer, its been installed allright, and I use composer for loads of other projects just fine, the autoloader loads everything else. 

`<?php

require "includes.php";

use PHPCoord\CoordinateReferenceSystem\Geographic2D;
use PHPCoord\GeographicPoint;
use PHPCoord\UnitOfMeasure\Angle\Degree;
..`

**Comment by kasperkamperman** [comment]
Thanks @sttrsttr. I updated my php version to PHP8. 

After that I upgraded to (v3.1.1 => v4.3.0) by running ```composer require php-coord/php-coord``` again. 

Error stays the same.

**Comment by dvdoug** [comment]
Yes, the minimum PHP version for v4 is 7.3.

@kasperkamperman to confirm, you are still having problems? I just did a copy/paste of that sample code into a fresh directory and it worked fine for me 🤔 See https://gist.github.com/dvdoug/ef045a4c0e5c6a7f932446198c1719ae

**Comment by kasperkamperman** [comment]
A line further in the code, that I overlooked, caused this problem. Somehow it threw the error message on the line where "projected" was used. 

Maybe good to add the minimum version needed to the readme (although I should have checked the composer.json). 

Thanks for the clean example and helping out.
