### ISSUE TITLE
Lat/long from eastings & northings v4

### ISSUE THREAD

**Issue by turtle0x1** [dvdoug/PHPCoord#36]
Hey, nice library - I susspect im being stupid but alot of the existing code / references online point to old versions, reading the docs you provide an example but its not clear to me what todo in the following situation;

How do you arrive at the lat/long pair that would match the output of online tools? (at least the ones returned by a UK based google search?)

Take the following example from the ordnance survey data and using [this link](https://www.latlong.net/convert-address-to-lat-long.html) for geocoding;

| Postcode | Eastings | Northings | 
| --------- | -------- | ----------- |
| "BH1 1AA" | 409722 | 92041 | 

If you encode the the postcode using the link above you arrive at `50.727612, -1.861430`, if you use the code copied from the documentation [here](https://www.phpcoord.net/en/stable/coordinate_conversions_easy.html)

```php
<?php
require __DIR__ . "/vendor/autoload.php";
use PHPCoord\CoordinateReferenceSystem\Projected;
use PHPCoord\ProjectedPoint;
use PHPCoord\UTMPoint;
use PHPCoord\UnitOfMeasure\Length\Metre;
use PHPCoord\CoordinateReferenceSystem\Geographic2D;

$from = ProjectedPoint::createFromEastingNorthing(
    new Metre(409722),
    new Metre(92041),
    Projected::fromSRID(Projected::EPSG_OSGB36_BRITISH_NATIONAL_GRID)
);
$toCRS = Projected::fromSRID(Projected::EPSG_WGS_84_UTM_ZONE_31N);
$to = $from->convert($toCRS);
echo $to;
```
You don't get a similar result, Ive experimented with a few different constants from the `Projected` class but with no luck, am I using the wrong ones?

**Comment by dvdoug** [comment]
Hello

For lat/long you want a `Geographic` CRS (see https://www.phpcoord.net/en/stable/creating_points_geographic.html)

```
$toCRS = Geographic2D::fromSRID(Geographic2D::EPSG_WGS_84); GPS/Google maps
$to = $from->convert($toCRS);

or

$toCRS = Geographic2D::fromSRID(Geographic2D::EPSG_OSGB36); // OS maps, also Bing I think
$to = $from->convert($toCRS);
```

**Comment by dvdoug** [comment]
Actually https://www.phpcoord.net/en/stable/primer.html#coordinate-reference-systems-crss might be a better page in the docs to explain the different CRS types

**Comment by turtle0x1** [comment]
Thanks for the fast response! If I run the following; 
```php
require __DIR__ . "/vendor/autoload.php";
use PHPCoord\CoordinateReferenceSystem\Projected;
use PHPCoord\ProjectedPoint;
use PHPCoord\UnitOfMeasure\Length\Metre;
use PHPCoord\CoordinateReferenceSystem\Geographic2D;

$from = ProjectedPoint::createFromEastingNorthing(
    new Metre(92041),
    new Metre(409722),
   Projected::fromSRID(Projected::EPSG_OSGB36_BRITISH_NATIONAL_GRID)
);
$toCRS = Geographic2D::fromSRID(Geographic2D::EPSG_WGS_84); //GPS/Google maps
$to = $from->convert($toCRS);
echo $to;
```

I get

```
 Unable to perform conversion, please file a bug if you think this is incorrect
```

**Comment by dvdoug** [comment]
```
    new Metre(92041),
    new Metre(409722),
```

I think you've got eastings/northings swapped 🤞

**Comment by turtle0x1** [comment]
You beat me to the edit, you were right i had the wrong way round!

I think this would be a great addition to the documentation under the section [this page](https://www.phpcoord.net/en/stable/coordinate_conversions_easy.html) as that's where I went to instinctively, thanks again!  😄

**Comment by dvdoug** [comment]
Awesome, had me worried for a second as I'm the UK too and I *know* that conversion is supposed to work...

That's a good suggestion about the docs, I'll add a projected->geographic example to it.
