### ISSUE TITLE
Bug: Transformations give wrong longitudes when longitude is outside -90 to 90 degrees

### ISSUE THREAD

**Issue by caffme** [dvdoug/PHPCoord#5]
I have created failing tests for this in pull #4 I found the bug in a real transform but the test used transform parameters intended to make no change to the coordinates.

Some sample longitudes input => output:
```
-180 => 0
-100 => 80
-90 => -90
-80 => -80
0 => 0
80 => 80
90 => 90
100 => -80
180 => -0
```

**Comment by dvdoug** [comment]
Hmm, thanks for this. The maths here is from the original code, so I guess I've got some light reading to do over xmas to try and figure out what's wrong here :/

**Comment by caffme** [comment]
Merry Christmas :)

I'd have fixed it if it was straight forward.

**Comment by dvdoug** [comment]
v1.1.2 includes the fix for this. Thanks for the bug report and the tests!
