### ISSUE TITLE
Retrieving Coordinate Systems to Display

### ISSUE THREAD

**Issue by bethanywallace** [dvdoug/PHPCoord#52]
Hi! Are there any built-in methods to query the stored Coordinate System, for example if a user populates a search box in the front-end it can then retrieve all Coordinate Systems matching the input. Or even to populate a drop down list so a user can select a Coordinate System to project from.

**Comment by dvdoug** [comment]
Hi @bethanywallace 

Depends on how sophisticated you want your search box to be - at the moment there are just `getSupportedSRIDs()` methods, both on each individual `CoordinateReferenceSystem` type (e.g. https://github.com/dvdoug/PHPCoord/blob/master/src/CoordinateReferenceSystem/Geographic2D.php#L4266) but also a super-version on `CoordinateReferenceSystem` itself, see https://github.com/dvdoug/PHPCoord/blob/master/src/CoordinateReferenceSystem/CoordinateReferenceSystem.php. Those will give you a full list of the constants to the descriptive names (I'll document this).

If you want to search the fuller descriptions that are in the code comments for each CRS there is not currently a built-in way to extract this, but I'd be open to adding one if that would be useful?
