### ISSUE TITLE
deprecation warning php 8: Optional parameter ... declared before required parameter

### ISSUE THREAD

**Issue by kasperkamperman** [dvdoug/PHPCoord#54]
`PHP Deprecated:  Optional parameter $height declared before required parameter $crs is implicitly treated as a required parameter in <myfolder>/vendor/php-coord/php-coord/src/GeographicPoint.php on line 132`

The source points to this function:
```
 public static function create(Angle $latitude, Angle $longitude, ?Length $height = null, Geographic $crs, ?DateTimeInterface $epoch = null): self
    {
        return new static($latitude, $longitude, $height, $crs, $epoch);
    }
        }
```

For completeness this is the function call I use, but I think this is caused by how the functions in the library are structured:

```
  $crs = Projected::fromSRID(Projected::EPSG_AMERSFOORT_RD_NEW);
  $from = ProjectedPoint::createFromEastingNorthing(
      new Metre($easting),
      new Metre($northing),
      $crs
  );
  
  $coords = (string) $from->convert(Geographic2D::fromSRID(Geographic2D::EPSG_WGS_84), true);
```

Info about this warning:
https://php.watch/versions/8.0/deprecate-required-param-after-optional

**Comment by dvdoug** [comment]
Hi @kasperkamperman 

It looks like you're using one of the v4.x versions, this was addressed in v5.0 which re-ordered the params: https://github.com/dvdoug/PHPCoord/releases/tag/v5.0.0

**Comment by kasperkamperman** [comment]
I have the most recent version:
```
"php-coord/php-coord": "^5.3",
"php-coord/datapack-europe": "^1.3"
```

**Comment by dvdoug** [comment]
Hi @kasperkamperman 

That might be what your `composer.json` is saying, but somehow that's not the version you've got installed. In v5.3, that function looks like the below, see https://github.com/dvdoug/PHPCoord/blob/v5.3.0/src/GeographicPoint.php#L136

```php
public static function create(Geographic2D|Geographic3D $crs, Angle $latitude, Angle $longitude, ?Length $height = null, ?DateTimeInterface $epoch = null): self
{
    return new static($crs, $latitude, $longitude, $height, $epoch);
}
```

As you can see the order of arguments is completely different

**Comment by kasperkamperman** [comment]
Thanks. Indeed I had the wrong folder. Sorry for that. 
Enjoy your weekend. 

Kasper
