### ISSUE TITLE
UnknownConversionException with ETRS89_TM35FIN_N_E

### ISSUE THREAD

**Issue by lasselehtinen** [dvdoug/PHPCoord#63]
Hi,

I am writing an API that generates random WGS84 coordinates in unit tests. These are then converted to ETRS89_TM35FIN_N_E. The limits for the coordinates are 60-70 and 20-30. These should be well within the bounds of ETRS89_TM35FIN_N_E. However with the random coordinate generation, I am sometimes getting an the exception below even though everything should be fine. 

`PHPCoord\Exception\UnknownConversionException  Unable to perform conversion, please file a bug if you think this is incorrect.`

WGS84 bounds for ETRS89_TM35FIN_N_E:
-16.1 32.88
40.18 84.73

```php
$from = GeographicPoint::create(
    Geographic2D::fromSRID(Geographic2D::EPSG_WGS_84),
    new Degree(68.754962),
    new Degree(23.258243),
    null
);

$toCRS = Projected::fromSRID(Projected::EPSG_ETRS89_TM35FIN_N_E);
$point = $from->convert($toCRS);
```

**Comment by lasselehtinen** [comment]
Of course if I set the ignoreBoundaryRestrictions to true, these conversions work fine. But the issue is that I am inside the boundaries so I would rather not force it to true?

**Comment by dvdoug** [comment]
Hi @lasselehtinen 

I've just plotted that point, and it seems to me that it's actually just over the border in Norway, not Finland so I think the exception is correct here?

![image](https://github.com/dvdoug/PHPCoord/assets/1571110/eba9bb84-32ee-4f96-acf5-4f1e7f98455b)

**Comment by lasselehtinen** [comment]
Thanks, I picked coordinates / bounding box that are always inside the borders and it seems to work now. I found two different sources for the bounding box for this projection. I assume the conversion is actually more stricter than either of these?

https://epsg.io/3067
https://spatialreference.org/ref/epsg/3067/

**Comment by dvdoug** [comment]
Note, those are not quite the same. You're using `EPSG_ETRS89_TM35FIN_N_E` which is EPSG 5048, you've linked to EPSG 3067 which in PHPCoord is `EPSG_ETRS89_TM35FIN_E_N`.

Official EPSG links for those two are:
- https://epsg.org/crs_5048/ETRS89-TM35FIN-N-E.html -> Extent is Finland only
- https://epsg.org/crs_3047/ETRS89-UTM-zone-35N-N-E.html -> Extent is a vertical slice of Europe

**Comment by lasselehtinen** [comment]
Well I learned something about projections then. Thanks for your assistance, I will close the ticket.
