### ISSUE TITLE
Failure to calculate long distances with vicenty

### ISSUE THREAD

**Issue by mmilet** [dvdoug/PHPCoord#64]
Hello,

I've been trying to calculate distances between many points pairs (decimal degrees) and WGS 84 CRS.
While most distances are properly calculated some are getting stuck in the Vicenty calculation, more specifically within the "Antipodal case" code block, where it loops over four $sinAlpha values over and over, indefinitely.

I've tried the following script:
```php
<?php

use PHPCoord\CoordinateReferenceSystem\Geographic2D;
use PHPCoord\Point\GeographicPoint;
use PHPCoord\UnitOfMeasure\Angle\Degree;

require_once './vendor/autoload.php';

$lat1 = -33.81083333;
$lon1 = 19.91;
$lat2 = -18.2;
$lon2 = -178.8161111;

$crs = Geographic2D::fromSRID(Geographic2D::EPSG_WGS_84);

$from = GeographicPoint::create($crs, new Degree($lat1), new Degree($lon1));
$to = GeographicPoint::create($crs, new Degree($lat2), new Degree($lon2));

// Hangs in here indefinitely.
$distance = $from->calculateDistance($to);
```

I also tried the above values in `GeographicPointTest::testDistanceCalculationAntipodeWikiExample1()`, the test hangs in the very same way

Thanks for all the work put in this library!

**Comment by dvdoug** [comment]
I can reproduce :(

The Antipode case is taken from https://github.com/dvdoug/PHPCoord/blob/master/resources/papers/Vincenty%2075b.pdf which I think I've transcribed correctly, but perhaps not. I'll take a look, see if I can spot the error

**Comment by dvdoug** [comment]
I cannot find any errors in transcription from the antipodal Vincenty formula, but I think in some cases floating point not being proper decimals are causing it to do weird things.

I've got a prototype of a different algorithm (Karney) working which handles this case better although is immensely complicated in comparison!
