### ISSUE TITLE
Possible rounding error when converting Geographic2D::EPSG_IRENET95 to Projected::EPSG_TM75_IRISH_GRID

### ISSUE THREAD

**Issue by lukewatts** [dvdoug/PHPCoord#66]
I'm probably doing something wrong, but I need to convert a latitude/longitude to an Irish Grid Reference (e.g. O1573234668)

```php
// The Spire, Dublin
$latitude = 53.349803;
$longitude = -6.2628240;

$crs    = Geographic2D::fromSRID(Geographic2D::EPSG_IRENET95);
$point  = GeographicPoint::create(
    crs:        $crs,
    latitude:   $latitude,
    longitude:  $longitude,
);

$irishGridCRS = Projected::fromSRID(Projected::EPSG_TM75_IRISH_GRID);
/** @var IrishGridPoint */
$irishGridPoint = $point->convert($irishGridCRS);

$result = $irishGridPoint->asGridReference(10);

echo $result; // O1573234668
```

After this I'm getting O1573234668, but all the online tools are saying it should be O1571734669
![image](https://github.com/user-attachments/assets/b0487355-73b4-4a59-8036-595095bafe9b)

If I change these lines 99 & 100 in `PHPCoord\Point\IrishGridPoint` it fixes it:

From:
```php
$easting = str_pad((string) round($x), $halfLength, '0', STR_PAD_LEFT);
$northing = str_pad((string) round($y), $halfLength, '0', STR_PAD_LEFT);
```

To:
```php
$easting = str_pad((string) intval($x), $halfLength, '0', STR_PAD_LEFT);
$northing = str_pad((string) intval($y), $halfLength, '0', STR_PAD_LEFT);
```

If there is a better way of getting from lat/lon to the correct grid reference please let me know. 

Thanks,
Luke

**Comment by dvdoug** [comment]
Hi @lukewatts 

The FAQ from the website you screenshotted suggests that the lat/long it uses is from WGS84, which is close to but not quite the same thing as IRE95/EPSG89. PHPCoord gives the same results (only a 1mm difference) as the well-known `proj` tool here so I'm pretty confident in the accuracy

PHPCoord
Easting = `315732.48768468`
Northing = `234667.59826906`

Proj
Easting = `315732.48828881`
Northing = `234667.59940034`

```
cs2cs -d 8 EPSG:4173 EPSG:29903 << EOF
53.349803N 6.2628240W
EOF
315732.48828881 234667.59940034 0.00000000
```

**Comment by lukewatts** [comment]
Thank you. I did notice the numbers were closer after swapping `round` for `intval` when calculating the easting. But I've been using the IRENET95 -> TM75 Conversion, so that could be nonsense on my part.

So should I be doin the conversion the way I am, or is there a better/more accurate way?

Also, thanks for all the work on this package. I'd be lost without it for this current project

**Comment by dvdoug** [comment]
Yes indeed, you've found a bug there with wrongly rounding rather than truncating - this used to work, but I broke it in January when fixing an edge case

I've also figured out the discrepancy between the OSI converter and PHPCoord, the TM75 -> Grid conversion was fine, but PHPCoord was using a slightly less accurate conversion between IRENET95 and TM75 than the official converter was. That's now fixed too

PS thanks for the donation
